---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-order
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http       
      containerPort: 8700
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: "Never"
- op: remove
  path: /spec/template/spec/securityContext
- op: remove
  path: /spec/template/spec/automountServiceAccountToken
- op: remove
  path: /spec/template/spec/containers/0/securityContext
- op: remove
  path: /spec/template/spec/containers/0/resources
